# Generated by Django 5.0.6 on 2024-05-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0002_blogpost_generated_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='generated_content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_link',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_title',
        ),
    ]
