# Generated by Django 5.0.6 on 2024-05-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0003_remove_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
