# Generated by Django 5.0.6 on 2024-05-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
