# Generated by Django 5.0.6 on 2024-05-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0006_delete_blogpost'),
    ]

    operations = [
    ]
